//! SDK 2013 ai_default.cpp schedule table (CAI_BaseNPC default schedules) as data:
//! (schedule, [(task, argument)], [interrupt conditions]). Generated from the SDK
//! definitions by the cloud session (2026-10-10); arguments keep the SDK spelling
//! ("SCHEDULE:x", "ACTIVITY:x", "TASK:x" or a number).

pub type ScheduleData = (
    &'static str,
    &'static [(&'static str, &'static str)],
    &'static [&'static str],
);

pub const DEFAULT_SCHEDULES: &[ScheduleData] = &[
    (
        "SCHED_FAIL",
        &[
            ("TASK_SET_FAIL_SCHEDULE", "SCHEDULE:SCHED_FAIL_NOSTOP"),
            ("TASK_STOP_MOVING", "0"),
            ("TASK_SET_ACTIVITY", "ACTIVITY:ACT_IDLE"),
            ("TASK_WAIT", "1"),
            ("TASK_WAIT_PVS", "0"),
        ],
        &[
            "COND_CAN_RANGE_ATTACK1",
            "COND_CAN_RANGE_ATTACK2",
            "COND_CAN_MELEE_ATTACK1",
            "COND_CAN_MELEE_ATTACK2",
            "COND_GIVE_WAY",
        ],
    ),
    (
        "SCHED_FAIL_NOSTOP",
        &[
            ("TASK_SET_ACTIVITY", "ACTIVITY:ACT_IDLE"),
            ("TASK_WAIT", "1"),
            ("TASK_WAIT_PVS", "0"),
        ],
        &[
            "COND_CAN_RANGE_ATTACK1",
            "COND_CAN_RANGE_ATTACK2",
            "COND_CAN_MELEE_ATTACK1",
            "COND_CAN_MELEE_ATTACK2",
            "COND_GIVE_WAY",
        ],
    ),
    (
        "SCHED_IDLE_STAND",
        &[
            ("TASK_STOP_MOVING", "1"),
            ("TASK_SET_ACTIVITY", "ACTIVITY:ACT_IDLE"),
            ("TASK_WAIT", "5"),
            ("TASK_WAIT_PVS", "0"),
        ],
        &[
            "COND_NEW_ENEMY",
            "COND_SEE_FEAR",
            "COND_LIGHT_DAMAGE",
            "COND_HEAVY_DAMAGE",
            "COND_SMELL",
            "COND_PROVOKED",
            "COND_GIVE_WAY",
            "COND_HEAR_PLAYER",
            "COND_HEAR_DANGER",
            "COND_HEAR_COMBAT",
            "COND_HEAR_BULLET_IMPACT",
            "COND_IDLE_INTERRUPT",
        ],
    ),
    (
        "SCHED_WAIT_FOR_SCRIPT",
        &[("TASK_STOP_MOVING", "0"), ("TASK_WAIT_INDEFINITE", "0")],
        &["COND_LIGHT_DAMAGE", "COND_HEAVY_DAMAGE"],
    ),
    (
        "SCHED_IDLE_WALK",
        &[
            ("TASK_WALK_PATH", "9999"),
            ("TASK_WAIT_FOR_MOVEMENT", "0"),
            ("TASK_WAIT_PVS", "0"),
        ],
        &[
            "COND_NEW_ENEMY",
            "COND_SEE_ENEMY",
            "COND_LIGHT_DAMAGE",
            "COND_HEAVY_DAMAGE",
            "COND_SMELL",
            "COND_PROVOKED",
            "COND_HEAR_COMBAT",
            "COND_HEAR_BULLET_IMPACT",
        ],
    ),
    (
        "SCHED_NEW_WEAPON",
        &[
            ("TASK_STOP_MOVING", "0"),
            ("TASK_SET_TOLERANCE_DISTANCE", "5"),
            ("TASK_GET_PATH_TO_TARGET_WEAPON", "0"),
            ("TASK_WEAPON_RUN_PATH", "0"),
            ("TASK_STOP_MOVING", "0"),
            ("TASK_FACE_TARGET", "0"),
            ("TASK_WEAPON_PICKUP", "0"),
            ("TASK_WAIT", "1"),
        ],
        &["COND_HEAR_DANGER"],
    ),
    (
        "SCHED_NEW_WEAPON_CHEAT",
        &[("TASK_WEAPON_CREATE", "0")],
        &[],
    ),
    (
        "SCHED_SWITCH_TO_PENDING_WEAPON",
        &[
            ("TASK_STOP_MOVING", "0"),
            ("TASK_PLAY_SEQUENCE", "ACTIVITY:ACT_DROP_WEAPON"),
            ("TASK_CREATE_PENDING_WEAPON", "0"),
        ],
        &[],
    ),
    (
        "SCHED_GET_HEALTHKIT",
        &[
            ("TASK_STOP_MOVING", "0"),
            ("TASK_SET_TOLERANCE_DISTANCE", "5"),
            ("TASK_GET_PATH_TO_TARGET_WEAPON", "0"),
            ("TASK_ITEM_RUN_PATH", "0"),
            ("TASK_STOP_MOVING", "0"),
            ("TASK_FACE_TARGET", "0"),
            ("TASK_ITEM_PICKUP", "0"),
        ],
        &[],
    ),
    (
        "SCHED_RANGE_ATTACK1",
        &[
            ("TASK_STOP_MOVING", "0"),
            ("TASK_FACE_ENEMY", "0"),
            ("TASK_ANNOUNCE_ATTACK", "1"),
            ("TASK_RANGE_ATTACK1", "0"),
        ],
        &[
            "COND_NEW_ENEMY",
            "COND_ENEMY_DEAD",
            "COND_LIGHT_DAMAGE",
            "COND_HEAVY_DAMAGE",
            "COND_ENEMY_OCCLUDED",
            "COND_NO_PRIMARY_AMMO",
            "COND_HEAR_DANGER",
            "COND_WEAPON_BLOCKED_BY_FRIEND",
            "COND_WEAPON_SIGHT_OCCLUDED",
        ],
    ),
    (
        "SCHED_RANGE_ATTACK2",
        &[
            ("TASK_STOP_MOVING", "0"),
            ("TASK_FACE_ENEMY", "0"),
            ("TASK_ANNOUNCE_ATTACK", "2"),
            ("TASK_RANGE_ATTACK2", "0"),
        ],
        &[
            "COND_NEW_ENEMY",
            "COND_ENEMY_DEAD",
            "COND_LIGHT_DAMAGE",
            "COND_HEAVY_DAMAGE",
            "COND_ENEMY_OCCLUDED",
            "COND_NO_SECONDARY_AMMO",
            "COND_HEAR_DANGER",
        ],
    ),
    (
        "SCHED_AMBUSH",
        &[
            ("TASK_STOP_MOVING", "0"),
            ("TASK_SET_ACTIVITY", "ACTIVITY:ACT_IDLE"),
            ("TASK_WAIT_INDEFINITE", "0"),
        ],
        &[
            "COND_NEW_ENEMY",
            "COND_LIGHT_DAMAGE",
            "COND_HEAVY_DAMAGE",
            "COND_PROVOKED",
        ],
    ),
    (
        "SCHED_WAKE_ANGRY",
        &[
            ("TASK_STOP_MOVING", "0"),
            ("TASK_SET_ACTIVITY", "ACTIVITY:ACT_IDLE"),
            ("TASK_SOUND_WAKE", "0"),
            ("TASK_FACE_IDEAL", "0"),
            ("TASK_SET_ACTIVITY", "ACTIVITY:ACT_IDLE"),
        ],
        &[],
    ),
    (
        "SCHED_ALERT_FACE",
        &[
            ("TASK_STOP_MOVING", "0"),
            ("TASK_FACE_IDEAL", "0"),
            ("TASK_SET_ACTIVITY", "ACTIVITY:ACT_IDLE"),
        ],
        &[
            "COND_NEW_ENEMY",
            "COND_SEE_FEAR",
            "COND_LIGHT_DAMAGE",
            "COND_HEAVY_DAMAGE",
            "COND_PROVOKED",
        ],
    ),
    (
        "SCHED_ALERT_FACE_BESTSOUND",
        &[
            ("TASK_STORE_BESTSOUND_REACTORIGIN_IN_SAVEPOSITION", "0"),
            ("TASK_STOP_MOVING", "0"),
            ("TASK_FACE_SAVEPOSITION", "0"),
            ("TASK_SET_ACTIVITY", "ACTIVITY:ACT_IDLE"),
            ("TASK_WAIT", "1.5"),
            ("TASK_FACE_REASONABLE", "0"),
        ],
        &[
            "COND_NEW_ENEMY",
            "COND_SEE_FEAR",
            "COND_LIGHT_DAMAGE",
            "COND_HEAVY_DAMAGE",
            "COND_PROVOKED",
        ],
    ),
    (
        "SCHED_ALERT_REACT_TO_COMBAT_SOUND",
        &[("TASK_SET_SCHEDULE", "SCHEDULE:SCHED_ALERT_FACE_BESTSOUND")],
        &[],
    ),
    (
        "SCHED_ALERT_SCAN",
        &[
            ("TASK_STOP_MOVING", "0"),
            ("TASK_WAIT", "0.5"),
            ("TASK_TURN_LEFT", "180"),
            ("TASK_WAIT", "0.5"),
            ("TASK_TURN_LEFT", "180"),
        ],
        &["COND_NEW_ENEMY"],
    ),
    (
        "SCHED_ALERT_STAND",
        &[
            ("TASK_STOP_MOVING", "0"),
            ("TASK_FACE_REASONABLE", "0"),
            ("TASK_SET_ACTIVITY", "ACTIVITY:ACT_IDLE"),
            ("TASK_WAIT", "20"),
            ("TASK_SUGGEST_STATE", "STATE:IDLE"),
        ],
        &[
            "COND_NEW_ENEMY",
            "COND_SEE_ENEMY",
            "COND_SEE_FEAR",
            "COND_LIGHT_DAMAGE",
            "COND_HEAVY_DAMAGE",
            "COND_PROVOKED",
            "COND_SMELL",
            "COND_HEAR_COMBAT",
            "COND_HEAR_WORLD",
            "COND_HEAR_PLAYER",
            "COND_HEAR_DANGER",
            "COND_HEAR_BULLET_IMPACT",
            "COND_IDLE_INTERRUPT",
            "COND_GIVE_WAY",
        ],
    ),
    (
        "SCHED_ALERT_WALK",
        &[
            ("TASK_WALK_PATH", "0"),
            ("TASK_WAIT_FOR_MOVEMENT", "0"),
            ("TASK_WAIT_PVS", "0"),
        ],
        &[
            "COND_NEW_ENEMY",
            "COND_SEE_ENEMY",
            "COND_SEE_FEAR",
            "COND_ENEMY_DEAD",
            "COND_LIGHT_DAMAGE",
            "COND_HEAVY_DAMAGE",
            "COND_HEAR_DANGER",
            "COND_CAN_RANGE_ATTACK1",
            "COND_CAN_RANGE_ATTACK2",
            "COND_CAN_MELEE_ATTACK1",
            "COND_CAN_MELEE_ATTACK2",
        ],
    ),
    (
        "SCHED_INVESTIGATE_SOUND",
        &[
            ("TASK_STOP_MOVING", "0"),
            ("TASK_STORE_LASTPOSITION", "0"),
            ("TASK_GET_PATH_TO_BESTSOUND", "0"),
            ("TASK_FACE_IDEAL", "0"),
            ("TASK_RUN_PATH", "0"),
            ("TASK_WAIT_FOR_MOVEMENT", "0"),
            ("TASK_STOP_MOVING", "0"),
            ("TASK_WAIT", "5"),
            ("TASK_GET_PATH_TO_LASTPOSITION", "0"),
            ("TASK_WALK_PATH", "0"),
            ("TASK_WAIT_FOR_MOVEMENT", "0"),
            ("TASK_STOP_MOVING", "0"),
            ("TASK_CLEAR_LASTPOSITION", "0"),
            ("TASK_FACE_REASONABLE", "0"),
        ],
        &[
            "COND_NEW_ENEMY",
            "COND_SEE_FEAR",
            "COND_SEE_ENEMY",
            "COND_LIGHT_DAMAGE",
            "COND_HEAVY_DAMAGE",
            "COND_HEAR_DANGER",
        ],
    ),
    (
        "SCHED_COMBAT_STAND",
        &[
            ("TASK_STOP_MOVING", "0"),
            ("TASK_SET_ACTIVITY", "ACTIVITY:ACT_IDLE"),
            ("TASK_WAIT_INDEFINITE", "0"),
        ],
        &[
            "COND_NEW_ENEMY",
            "COND_ENEMY_DEAD",
            "COND_LIGHT_DAMAGE",
            "COND_HEAVY_DAMAGE",
            "COND_SEE_ENEMY",
            "COND_CAN_RANGE_ATTACK1",
            "COND_CAN_RANGE_ATTACK2",
            "COND_CAN_MELEE_ATTACK1",
            "COND_CAN_MELEE_ATTACK2",
            "COND_IDLE_INTERRUPT",
        ],
    ),
    (
        "SCHED_COMBAT_WALK",
        &[
            ("TASK_WALK_PATH", "0"),
            ("TASK_WAIT_FOR_MOVEMENT", "0"),
            ("TASK_WAIT_PVS", "0"),
        ],
        &[
            "COND_NEW_ENEMY",
            "COND_ENEMY_DEAD",
            "COND_LIGHT_DAMAGE",
            "COND_HEAVY_DAMAGE",
            "COND_HEAR_DANGER",
            "COND_CAN_RANGE_ATTACK1",
            "COND_CAN_RANGE_ATTACK2",
            "COND_CAN_MELEE_ATTACK1",
            "COND_CAN_MELEE_ATTACK2",
        ],
    ),
    (
        "SCHED_COMBAT_FACE",
        &[
            ("TASK_STOP_MOVING", "0"),
            ("TASK_SET_ACTIVITY", "ACTIVITY:ACT_IDLE"),
            ("TASK_FACE_ENEMY", "0"),
        ],
        &[
            "COND_CAN_RANGE_ATTACK1",
            "COND_CAN_RANGE_ATTACK2",
            "COND_CAN_MELEE_ATTACK1",
            "COND_CAN_MELEE_ATTACK2",
            "COND_NEW_ENEMY",
            "COND_ENEMY_DEAD",
        ],
    ),
    (
        "SCHED_COMBAT_SWEEP",
        &[
            ("TASK_TURN_LEFT", "45"),
            ("TASK_WAIT", "2"),
            ("TASK_TURN_RIGHT", "45"),
            ("TASK_WAIT", "2"),
        ],
        &[
            "COND_NEW_ENEMY",
            "COND_SEE_ENEMY",
            "COND_LIGHT_DAMAGE",
            "COND_HEAVY_DAMAGE",
            "COND_CAN_RANGE_ATTACK1",
            "COND_CAN_RANGE_ATTACK2",
            "COND_HEAR_DANGER",
            "COND_HEAR_WORLD",
        ],
    ),
    (
        "SCHED_STANDOFF",
        &[
            ("TASK_STOP_MOVING", "0"),
            ("TASK_SET_ACTIVITY", "ACTIVITY:ACT_IDLE"),
            ("TASK_WAIT_FACE_ENEMY", "2"),
        ],
        &[
            "COND_CAN_RANGE_ATTACK1",
            "COND_CAN_RANGE_ATTACK2",
            "COND_CAN_MELEE_ATTACK1",
            "COND_CAN_MELEE_ATTACK2",
            "COND_ENEMY_DEAD",
            "COND_NEW_ENEMY",
            "COND_HEAR_DANGER",
        ],
    ),
    (
        "SCHED_ARM_WEAPON",
        &[
            ("TASK_STOP_MOVING", "0"),
            ("TASK_FACE_IDEAL", "0"),
            ("TASK_PLAY_SEQUENCE", "ACTIVITY:ACT_ARM"),
        ],
        &[],
    ),
    (
        "SCHED_DISARM_WEAPON",
        &[
            ("TASK_STOP_MOVING", "0"),
            ("TASK_FACE_IDEAL", "0"),
            ("TASK_PLAY_SEQUENCE", "ACTIVITY:ACT_DISARM"),
        ],
        &[],
    ),
    (
        "SCHED_HIDE_AND_RELOAD",
        &[
            ("TASK_STOP_MOVING", "0"),
            ("TASK_SET_FAIL_SCHEDULE", "SCHEDULE:SCHED_RELOAD"),
            ("TASK_FIND_COVER_FROM_ENEMY", "0"),
            ("TASK_RUN_PATH", "0"),
            ("TASK_WAIT_FOR_MOVEMENT", "0"),
            ("TASK_REMEMBER", "MEMORY:INCOVER"),
            ("TASK_FACE_ENEMY", "0"),
            ("TASK_SET_SCHEDULE", "SCHEDULE:SCHED_RELOAD"),
        ],
        &["COND_HEAR_DANGER"],
    ),
    (
        "SCHED_RELOAD",
        &[("TASK_STOP_MOVING", "0"), ("TASK_RELOAD", "0")],
        &["COND_HEAR_DANGER"],
    ),
    (
        "SCHED_MELEE_ATTACK1",
        &[
            ("TASK_STOP_MOVING", "0"),
            ("TASK_FACE_ENEMY", "0"),
            ("TASK_ANNOUNCE_ATTACK", "1"),
            ("TASK_MELEE_ATTACK1", "0"),
        ],
        &[
            "COND_NEW_ENEMY",
            "COND_ENEMY_DEAD",
            "COND_LIGHT_DAMAGE",
            "COND_HEAVY_DAMAGE",
            "COND_ENEMY_OCCLUDED",
        ],
    ),
    (
        "SCHED_MELEE_ATTACK2",
        &[
            ("TASK_STOP_MOVING", "0"),
            ("TASK_FACE_ENEMY", "0"),
            ("TASK_ANNOUNCE_ATTACK", "2"),
            ("TASK_MELEE_ATTACK2", "0"),
        ],
        &[
            "COND_NEW_ENEMY",
            "COND_ENEMY_DEAD",
            "COND_LIGHT_DAMAGE",
            "COND_HEAVY_DAMAGE",
            "COND_ENEMY_OCCLUDED",
        ],
    ),
    (
        "SCHED_SPECIAL_ATTACK1",
        &[
            ("TASK_STOP_MOVING", "0"),
            ("TASK_FACE_ENEMY", "0"),
            ("TASK_SPECIAL_ATTACK1", "0"),
        ],
        &[
            "COND_NEW_ENEMY",
            "COND_ENEMY_DEAD",
            "COND_LIGHT_DAMAGE",
            "COND_HEAVY_DAMAGE",
            "COND_ENEMY_OCCLUDED",
            "COND_NO_PRIMARY_AMMO",
            "COND_HEAR_DANGER",
        ],
    ),
    (
        "SCHED_SPECIAL_ATTACK2",
        &[
            ("TASK_STOP_MOVING", "0"),
            ("TASK_FACE_ENEMY", "0"),
            ("TASK_SPECIAL_ATTACK2", "0"),
        ],
        &[
            "COND_NEW_ENEMY",
            "COND_ENEMY_DEAD",
            "COND_LIGHT_DAMAGE",
            "COND_HEAVY_DAMAGE",
            "COND_ENEMY_OCCLUDED",
            "COND_NO_SECONDARY_AMMO",
            "COND_HEAR_DANGER",
        ],
    ),
    (
        "SCHED_CHASE_ENEMY",
        &[
            ("TASK_STOP_MOVING", "0"),
            (
                "TASK_SET_FAIL_SCHEDULE",
                "SCHEDULE:SCHED_CHASE_ENEMY_FAILED",
            ),
            ("TASK_GET_CHASE_PATH_TO_ENEMY", "300"),
            ("TASK_RUN_PATH", "0"),
            ("TASK_WAIT_FOR_MOVEMENT", "0"),
            ("TASK_FACE_ENEMY", "0"),
        ],
        &[
            "COND_NEW_ENEMY",
            "COND_ENEMY_DEAD",
            "COND_ENEMY_UNREACHABLE",
            "COND_CAN_RANGE_ATTACK1",
            "COND_CAN_MELEE_ATTACK1",
            "COND_CAN_RANGE_ATTACK2",
            "COND_CAN_MELEE_ATTACK2",
            "COND_TOO_CLOSE_TO_ATTACK",
            "COND_TASK_FAILED",
            "COND_LOST_ENEMY",
            "COND_BETTER_WEAPON_AVAILABLE",
            "COND_HEAR_DANGER",
        ],
    ),
    (
        "SCHED_TARGET_FACE",
        &[
            ("TASK_STOP_MOVING", "0"),
            ("TASK_SET_ACTIVITY", "ACTIVITY:ACT_IDLE"),
            ("TASK_FACE_TARGET", "0"),
        ],
        &[
            "COND_CAN_RANGE_ATTACK1",
            "COND_CAN_RANGE_ATTACK2",
            "COND_CAN_MELEE_ATTACK1",
            "COND_CAN_MELEE_ATTACK2",
            "COND_NEW_ENEMY",
            "COND_ENEMY_DEAD",
        ],
    ),
    (
        "SCHED_TARGET_CHASE",
        &[
            ("TASK_STOP_MOVING", "0"),
            ("TASK_GET_PATH_TO_TARGET", "0"),
            ("TASK_RUN_PATH", "0"),
            ("TASK_WAIT_FOR_MOVEMENT", "0"),
        ],
        &[
            "COND_NEW_ENEMY",
            "COND_ENEMY_DEAD",
            "COND_ENEMY_UNREACHABLE",
            "COND_CAN_RANGE_ATTACK1",
            "COND_CAN_MELEE_ATTACK1",
            "COND_CAN_RANGE_ATTACK2",
            "COND_CAN_MELEE_ATTACK2",
            "COND_TOO_CLOSE_TO_ATTACK",
            "COND_TASK_FAILED",
            "COND_LOST_ENEMY",
            "COND_BETTER_WEAPON_AVAILABLE",
            "COND_HEAR_DANGER",
        ],
    ),
    (
        "SCHED_CHASE_ENEMY_FAILED",
        &[
            ("TASK_STOP_MOVING", "0"),
            ("TASK_WAIT", "0.2"),
            ("TASK_SET_FAIL_SCHEDULE", "SCHEDULE:SCHED_STANDOFF"),
            ("TASK_FIND_COVER_FROM_ENEMY", "0"),
            ("TASK_RUN_PATH", "0"),
            ("TASK_WAIT_FOR_MOVEMENT", "0"),
            ("TASK_REMEMBER", "MEMORY:INCOVER"),
            ("TASK_FACE_ENEMY", "0"),
            ("TASK_SET_ACTIVITY", "ACTIVITY:ACT_IDLE"),
            ("TASK_WAIT", "1"),
        ],
        &[
            "COND_NEW_ENEMY",
            "COND_ENEMY_DEAD",
            "COND_CAN_RANGE_ATTACK1",
            "COND_CAN_MELEE_ATTACK1",
            "COND_CAN_RANGE_ATTACK2",
            "COND_CAN_MELEE_ATTACK2",
            "COND_HEAR_DANGER",
            "COND_BETTER_WEAPON_AVAILABLE",
            "COND_LIGHT_DAMAGE",
            "COND_HEAVY_DAMAGE",
        ],
    ),
    (
        "SCHED_BACK_AWAY_FROM_SAVE_POSITION",
        &[
            ("TASK_STOP_MOVING", "0"),
            ("TASK_FIND_BACKAWAY_FROM_SAVEPOSITION", "0"),
            ("TASK_RUN_PATH", "0"),
            ("TASK_WAIT_FOR_MOVEMENT", "0"),
        ],
        &[],
    ),
    (
        "SCHED_BACK_AWAY_FROM_ENEMY",
        &[
            ("TASK_STOP_MOVING", "0"),
            ("TASK_STORE_ENEMY_POSITION_IN_SAVEPOSITION", "0"),
            ("TASK_FIND_BACKAWAY_FROM_SAVEPOSITION", "0"),
            ("TASK_RUN_PATH", "0"),
            ("TASK_WAIT_FOR_MOVEMENT", "0"),
        ],
        &[
            "COND_NEW_ENEMY",
            "COND_CAN_RANGE_ATTACK1",
            "COND_CAN_RANGE_ATTACK2",
            "COND_CAN_MELEE_ATTACK1",
            "COND_CAN_MELEE_ATTACK2",
        ],
    ),
    (
        "SCHED_SMALL_FLINCH",
        &[
            ("TASK_REMEMBER", "MEMORY:FLINCHED"),
            ("TASK_STOP_MOVING", "0"),
            ("TASK_SMALL_FLINCH", "0"),
        ],
        &[],
    ),
    (
        "SCHED_BIG_FLINCH",
        &[
            ("TASK_REMEMBER", "MEMORY:FLINCHED"),
            ("TASK_STOP_MOVING", "0"),
            ("TASK_BIG_FLINCH", "0"),
        ],
        &[],
    ),
    (
        "SCHED_NPC_FREEZE",
        &[("TASK_FREEZE", "0")],
        &["COND_NPC_UNFREEZE"],
    ),
    (
        "SCHED_DIE",
        &[
            ("TASK_STOP_MOVING", "0"),
            ("TASK_SOUND_DIE", "0"),
            ("TASK_DIE", "0"),
        ],
        &["COND_NO_CUSTOM_INTERRUPTS"],
    ),
    (
        "SCHED_DIE_RAGDOLL",
        &[("TASK_STOP_MOVING", "0"), ("TASK_SOUND_DIE", "0")],
        &["COND_NO_CUSTOM_INTERRUPTS"],
    ),
    (
        "SCHED_VICTORY_DANCE",
        &[
            ("TASK_STOP_MOVING", "0"),
            ("TASK_PLAY_SEQUENCE", "ACTIVITY:ACT_VICTORY_DANCE"),
            ("TASK_WAIT", "0"),
        ],
        &[],
    ),
    (
        "SCHED_SCRIPTED_WALK",
        &[
            ("TASK_PRE_SCRIPT", "0"),
            ("TASK_SET_TOLERANCE_DISTANCE", "2"),
            ("TASK_PUSH_SCRIPT_ARRIVAL_ACTIVITY", "0"),
            ("TASK_SCRIPT_WALK_TO_TARGET", "0"),
            ("TASK_WAIT_FOR_MOVEMENT", "0"),
            ("TASK_PLANT_ON_SCRIPT", "0"),
            ("TASK_FACE_SCRIPT", "0"),
            ("TASK_ENABLE_SCRIPT", "0"),
            ("TASK_WAIT_FOR_SCRIPT", "0"),
            ("TASK_PLAY_SCRIPT", "0"),
            ("TASK_PLAY_SCRIPT_POST_IDLE", "0"),
        ],
        &["COND_LIGHT_DAMAGE", "COND_HEAVY_DAMAGE"],
    ),
    (
        "SCHED_SCRIPTED_RUN",
        &[
            ("TASK_PRE_SCRIPT", "0"),
            ("TASK_SET_TOLERANCE_DISTANCE", "2"),
            ("TASK_PUSH_SCRIPT_ARRIVAL_ACTIVITY", "0"),
            ("TASK_SCRIPT_RUN_TO_TARGET", "0"),
            ("TASK_WAIT_FOR_MOVEMENT", "0"),
            ("TASK_PLANT_ON_SCRIPT", "0"),
            ("TASK_FACE_SCRIPT", "0"),
            ("TASK_ENABLE_SCRIPT", "0"),
            ("TASK_WAIT_FOR_SCRIPT", "0"),
            ("TASK_PLAY_SCRIPT", "0"),
            ("TASK_PLAY_SCRIPT_POST_IDLE", "0"),
        ],
        &["COND_LIGHT_DAMAGE", "COND_HEAVY_DAMAGE"],
    ),
    (
        "SCHED_SCRIPTED_CUSTOM_MOVE",
        &[
            ("TASK_PRE_SCRIPT", "0"),
            ("TASK_SET_TOLERANCE_DISTANCE", "2"),
            ("TASK_PUSH_SCRIPT_ARRIVAL_ACTIVITY", "0"),
            ("TASK_SCRIPT_CUSTOM_MOVE_TO_TARGET", "0"),
            ("TASK_WAIT_FOR_MOVEMENT", "0"),
            ("TASK_PLANT_ON_SCRIPT", "0"),
            ("TASK_FACE_SCRIPT", "0"),
            ("TASK_ENABLE_SCRIPT", "0"),
            ("TASK_WAIT_FOR_SCRIPT", "0"),
            ("TASK_PLAY_SCRIPT", "0"),
            ("TASK_PLAY_SCRIPT_POST_IDLE", "0"),
        ],
        &["COND_LIGHT_DAMAGE", "COND_HEAVY_DAMAGE"],
    ),
    (
        "SCHED_SCRIPTED_WAIT",
        &[
            ("TASK_PRE_SCRIPT", "0"),
            ("TASK_STOP_MOVING", "0"),
            ("TASK_ENABLE_SCRIPT", "0"),
            ("TASK_WAIT_FOR_SCRIPT", "0"),
            ("TASK_PLAY_SCRIPT", "0"),
            ("TASK_PLAY_SCRIPT_POST_IDLE", "0"),
        ],
        &["COND_LIGHT_DAMAGE", "COND_HEAVY_DAMAGE"],
    ),
    (
        "SCHED_SCRIPTED_FACE",
        &[
            ("TASK_PRE_SCRIPT", "0"),
            ("TASK_STOP_MOVING", "0"),
            ("TASK_FACE_SCRIPT", "0"),
            ("TASK_ENABLE_SCRIPT", "0"),
            ("TASK_WAIT_FOR_SCRIPT", "0"),
            ("TASK_PLAY_SCRIPT", "0"),
            ("TASK_PLAY_SCRIPT_POST_IDLE", "0"),
        ],
        &["COND_LIGHT_DAMAGE", "COND_HEAVY_DAMAGE"],
    ),
    (
        "SCHED_SCENE_GENERIC",
        &[
            ("TASK_SET_FAIL_SCHEDULE", "SCHEDULE:SCHED_SCENE_GENERIC"),
            ("TASK_STOP_MOVING", "0"),
            ("TASK_SET_ACTIVITY", "ACTIVITY:ACT_IDLE"),
            ("TASK_PLAY_SCENE", "0"),
            ("TASK_WAIT_FOR_MOVEMENT", "0"),
            ("TASK_STOP_MOVING", "0"),
            ("TASK_SET_SCHEDULE", "SCHEDULE:SCHED_SCENE_GENERIC"),
        ],
        &[],
    ),
    (
        "SCHED_COWER",
        &[
            ("TASK_STOP_MOVING", "0"),
            ("TASK_PLAY_SEQUENCE", "ACTIVITY:ACT_COWER"),
            ("TASK_WAIT_UNTIL_NO_DANGER_SOUND", "0"),
        ],
        &[],
    ),
    (
        "SCHED_TAKE_COVER_FROM_ORIGIN",
        &[
            ("TASK_SET_FAIL_SCHEDULE", "SCHEDULE:SCHED_FAIL_TAKE_COVER"),
            ("TASK_STOP_MOVING", "0"),
            ("TASK_FIND_COVER_FROM_ORIGIN", "0"),
            ("TASK_RUN_PATH", "0"),
            ("TASK_WAIT_FOR_MOVEMENT", "0"),
            ("TASK_REMEMBER", "MEMORY:INCOVER"),
            ("TASK_TURN_LEFT", "179"),
            ("TASK_SET_ACTIVITY", "ACTIVITY:ACT_IDLE"),
        ],
        &["COND_NEW_ENEMY"],
    ),
    (
        "SCHED_TAKE_COVER_FROM_BEST_SOUND",
        &[
            (
                "TASK_SET_FAIL_SCHEDULE",
                "SCHEDULE:SCHED_FLEE_FROM_BEST_SOUND",
            ),
            ("TASK_STOP_MOVING", "0"),
            ("TASK_STORE_BESTSOUND_REACTORIGIN_IN_SAVEPOSITION", "0"),
            ("TASK_FIND_COVER_FROM_BEST_SOUND", "0"),
            ("TASK_RUN_PATH", "0"),
            ("TASK_WAIT_FOR_MOVEMENT", "0"),
            ("TASK_REMEMBER", "MEMORY:INCOVER"),
            ("TASK_FACE_SAVEPOSITION", "0"),
            ("TASK_SET_ACTIVITY", "ACTIVITY:ACT_IDLE"),
        ],
        &["COND_NEW_ENEMY"],
    ),
    (
        "SCHED_FLEE_FROM_BEST_SOUND",
        &[
            ("TASK_SET_FAIL_SCHEDULE", "SCHEDULE:SCHED_COWER"),
            ("TASK_STORE_BESTSOUND_REACTORIGIN_IN_SAVEPOSITION", "0"),
            ("TASK_GET_PATH_AWAY_FROM_BEST_SOUND", "600"),
            ("TASK_RUN_PATH_FLEE", "100"),
            ("TASK_STOP_MOVING", "0"),
            ("TASK_FACE_SAVEPOSITION", "0"),
        ],
        &["COND_NEW_ENEMY"],
    ),
    (
        "SCHED_TAKE_COVER_FROM_ENEMY",
        &[
            ("TASK_SET_FAIL_SCHEDULE", "SCHEDULE:SCHED_FAIL_TAKE_COVER"),
            ("TASK_STOP_MOVING", "0"),
            ("TASK_WAIT", "0.2"),
            ("TASK_FIND_COVER_FROM_ENEMY", "0"),
            ("TASK_RUN_PATH", "0"),
            ("TASK_WAIT_FOR_MOVEMENT", "0"),
            ("TASK_REMEMBER", "MEMORY:INCOVER"),
            ("TASK_FACE_ENEMY", "0"),
            ("TASK_SET_ACTIVITY", "ACTIVITY:ACT_IDLE"),
            ("TASK_WAIT", "1"),
        ],
        &["COND_NEW_ENEMY", "COND_HEAR_DANGER"],
    ),
    (
        "SCHED_FAIL_TAKE_COVER",
        &[("TASK_SET_ACTIVITY", "ACTIVITY:ACT_IDLE")],
        &["COND_NEW_ENEMY"],
    ),
    (
        "SCHED_RUN_FROM_ENEMY",
        &[
            (
                "TASK_SET_FAIL_SCHEDULE",
                "SCHEDULE:SCHED_RUN_FROM_ENEMY_FALLBACK",
            ),
            ("TASK_STOP_MOVING", "0"),
            ("TASK_FIND_COVER_FROM_ENEMY", "0"),
            ("TASK_RUN_PATH", "0"),
            ("TASK_WAIT_FOR_MOVEMENT", "0"),
        ],
        &["COND_NEW_ENEMY", "COND_ENEMY_DEAD"],
    ),
    (
        "SCHED_RUN_FROM_ENEMY_FALLBACK",
        &[
            ("TASK_SET_FAIL_SCHEDULE", "SCHEDULE:SCHED_RUN_RANDOM"),
            ("TASK_STOP_MOVING", "0"),
            ("TASK_STORE_ENEMY_POSITION_IN_SAVEPOSITION", "0"),
            ("TASK_FIND_BACKAWAY_FROM_SAVEPOSITION", "0"),
            ("TASK_RUN_PATH", "0"),
            ("TASK_WAIT_FOR_MOVEMENT", "0"),
        ],
        &["COND_NEW_ENEMY", "COND_ENEMY_DEAD"],
    ),
    (
        "SCHED_RUN_FROM_ENEMY_MOB",
        &[
            ("TASK_SET_FAIL_SCHEDULE", "SCHEDULE:SCHED_RUN_RANDOM"),
            ("TASK_STOP_MOVING", "0"),
            ("TASK_STORE_ENEMY_POSITION_IN_SAVEPOSITION", "0"),
            ("TASK_FIND_BACKAWAY_FROM_SAVEPOSITION", "0"),
            ("TASK_RUN_PATH", "0"),
            ("TASK_WAIT_FOR_MOVEMENT", "0"),
        ],
        &["COND_HEAR_DANGER"],
    ),
    (
        "SCHED_FEAR_FACE",
        &[
            ("TASK_STOP_MOVING", "0"),
            ("TASK_SET_ACTIVITY", "ACTIVITY:ACT_IDLE"),
            ("TASK_FACE_ENEMY", "0"),
        ],
        &["COND_NEW_ENEMY", "COND_ENEMY_DEAD", "COND_SEE_ENEMY"],
    ),
    (
        "SCHED_FORCED_GO",
        &[
            ("TASK_SET_TOLERANCE_DISTANCE", "48"),
            ("TASK_SET_ROUTE_SEARCH_TIME", "3"),
            ("TASK_GET_PATH_TO_LASTPOSITION", "0"),
            ("TASK_WALK_PATH", "0"),
            ("TASK_WAIT_FOR_MOVEMENT", "0"),
        ],
        &[],
    ),
    (
        "SCHED_FORCED_GO_RUN",
        &[
            ("TASK_SET_TOLERANCE_DISTANCE", "48"),
            ("TASK_SET_ROUTE_SEARCH_TIME", "3"),
            ("TASK_GET_PATH_TO_LASTPOSITION", "0"),
            ("TASK_RUN_PATH", "0"),
            ("TASK_WAIT_FOR_MOVEMENT", "0"),
        ],
        &[],
    ),
    (
        "SCHED_MOVE_TO_WEAPON_RANGE",
        &[
            ("TASK_SET_FAIL_SCHEDULE", "SCHEDULE:SCHED_CHASE_ENEMY"),
            ("TASK_GET_PATH_TO_RANGE_ENEMY_LKP_LOS", "0"),
            ("TASK_RUN_PATH", "0"),
            ("TASK_WAIT_FOR_MOVEMENT", "0"),
            ("TASK_SET_SCHEDULE", "SCHEDULE:SCHED_COMBAT_FACE"),
        ],
        &[
            "COND_NEW_ENEMY",
            "COND_ENEMY_DEAD",
            "COND_LOST_ENEMY",
            "COND_CAN_RANGE_ATTACK1",
            "COND_CAN_MELEE_ATTACK1",
            "COND_CAN_RANGE_ATTACK2",
            "COND_CAN_MELEE_ATTACK2",
            "COND_HEAR_DANGER",
        ],
    ),
    (
        "SCHED_ESTABLISH_LINE_OF_FIRE",
        &[
            (
                "TASK_SET_FAIL_SCHEDULE",
                "SCHEDULE:SCHED_ESTABLISH_LINE_OF_FIRE_FALLBACK",
            ),
            ("TASK_GET_PATH_TO_ENEMY_LOS", "0"),
            ("TASK_SPEAK_SENTENCE", "1"),
            ("TASK_RUN_PATH", "0"),
            ("TASK_WAIT_FOR_MOVEMENT", "0"),
            ("TASK_SET_SCHEDULE", "SCHEDULE:SCHED_COMBAT_FACE"),
        ],
        &[
            "COND_NEW_ENEMY",
            "COND_ENEMY_DEAD",
            "COND_LOST_ENEMY",
            "COND_CAN_RANGE_ATTACK1",
            "COND_CAN_MELEE_ATTACK1",
            "COND_CAN_RANGE_ATTACK2",
            "COND_CAN_MELEE_ATTACK2",
            "COND_HEAR_DANGER",
        ],
    ),
    (
        "SCHED_SHOOT_ENEMY_COVER",
        &[
            ("TASK_STOP_MOVING", "0"),
            ("TASK_FACE_ENEMY", "0"),
            ("TASK_WAIT", "0.5"),
            ("TASK_RANGE_ATTACK1", "0"),
        ],
        &[
            "COND_ENEMY_DEAD",
            "COND_LIGHT_DAMAGE",
            "COND_HEAVY_DAMAGE",
            "COND_NO_PRIMARY_AMMO",
            "COND_HEAR_DANGER",
            "COND_WEAPON_BLOCKED_BY_FRIEND",
        ],
    ),
    (
        "SCHED_ESTABLISH_LINE_OF_FIRE_FALLBACK",
        &[
            ("TASK_STOP_MOVING", "0"),
            (
                "TASK_SET_FAIL_SCHEDULE",
                "SCHEDULE:SCHED_PRE_FAIL_ESTABLISH_LINE_OF_FIRE",
            ),
            ("TASK_GET_CHASE_PATH_TO_ENEMY", "300"),
            ("TASK_RUN_PATH", "0"),
            ("TASK_WAIT_FOR_MOVEMENT", "0"),
            ("TASK_FACE_ENEMY", "0"),
        ],
        &[
            "COND_NEW_ENEMY",
            "COND_ENEMY_DEAD",
            "COND_ENEMY_UNREACHABLE",
            "COND_CAN_RANGE_ATTACK1",
            "COND_CAN_MELEE_ATTACK1",
            "COND_CAN_RANGE_ATTACK2",
            "COND_CAN_MELEE_ATTACK2",
            "COND_TOO_CLOSE_TO_ATTACK",
            "COND_TASK_FAILED",
            "COND_LOST_ENEMY",
            "COND_BETTER_WEAPON_AVAILABLE",
            "COND_HEAR_DANGER",
        ],
    ),
    (
        "SCHED_PRE_FAIL_ESTABLISH_LINE_OF_FIRE",
        &[
            ("TASK_FACE_ENEMY", "0"),
            ("TASK_FACE_REASONABLE", "0"),
            ("TASK_IGNORE_OLD_ENEMIES", "0"),
            (
                "TASK_SET_SCHEDULE",
                "SCHEDULE:SCHED_FAIL_ESTABLISH_LINE_OF_FIRE",
            ),
        ],
        &[
            "COND_NEW_ENEMY",
            "COND_ENEMY_DEAD",
            "COND_CAN_RANGE_ATTACK1",
            "COND_CAN_MELEE_ATTACK1",
            "COND_CAN_RANGE_ATTACK2",
            "COND_CAN_MELEE_ATTACK2",
        ],
    ),
    (
        "SCHED_FAIL_ESTABLISH_LINE_OF_FIRE",
        &[("TASK_SET_ACTIVITY", "ACTIVITY:ACT_IDLE")],
        &[
            "COND_NEW_ENEMY",
            "COND_ENEMY_DEAD",
            "COND_LOST_ENEMY",
            "COND_CAN_RANGE_ATTACK1",
            "COND_CAN_MELEE_ATTACK1",
            "COND_CAN_RANGE_ATTACK2",
            "COND_CAN_MELEE_ATTACK2",
            "COND_HEAR_DANGER",
        ],
    ),
    (
        "SCHED_PATROL_RUN",
        &[
            ("TASK_SET_FAIL_SCHEDULE", "SCHEDULE:SCHED_COMBAT_FACE"),
            ("TASK_SET_ROUTE_SEARCH_TIME", "5"),
            ("TASK_GET_PATH_TO_RANDOM_NODE", "200"),
            ("TASK_RUN_PATH", "0"),
            ("TASK_WAIT_FOR_MOVEMENT", "0"),
        ],
        &[
            "COND_CAN_RANGE_ATTACK1",
            "COND_CAN_RANGE_ATTACK2",
            "COND_CAN_MELEE_ATTACK1",
            "COND_CAN_MELEE_ATTACK2",
            "COND_GIVE_WAY",
            "COND_NEW_ENEMY",
            "COND_SEE_ENEMY",
            "COND_SEE_FEAR",
            "COND_HEAR_COMBAT",
            "COND_HEAR_DANGER",
            "COND_HEAR_PLAYER",
            "COND_LIGHT_DAMAGE",
            "COND_HEAVY_DAMAGE",
            "COND_SMELL",
            "COND_PROVOKED",
        ],
    ),
    (
        "SCHED_IDLE_WANDER",
        &[
            ("TASK_SET_ROUTE_SEARCH_TIME", "5"),
            ("TASK_GET_PATH_TO_RANDOM_NODE", "200"),
            ("TASK_WALK_PATH", "0"),
            ("TASK_WAIT_FOR_MOVEMENT", "0"),
            ("TASK_WAIT_PVS", "0"),
        ],
        &[
            "COND_GIVE_WAY",
            "COND_HEAR_COMBAT",
            "COND_HEAR_DANGER",
            "COND_NEW_ENEMY",
            "COND_SEE_ENEMY",
            "COND_SEE_FEAR",
            "COND_LIGHT_DAMAGE",
            "COND_HEAVY_DAMAGE",
            "COND_IDLE_INTERRUPT",
        ],
    ),
    (
        "SCHED_PATROL_WALK",
        &[
            ("TASK_SET_ROUTE_SEARCH_TIME", "5"),
            ("TASK_GET_PATH_TO_RANDOM_NODE", "200"),
            ("TASK_WALK_PATH", "0"),
            ("TASK_WAIT_FOR_MOVEMENT", "0"),
        ],
        &[
            "COND_CAN_RANGE_ATTACK1",
            "COND_CAN_RANGE_ATTACK2",
            "COND_CAN_MELEE_ATTACK1",
            "COND_CAN_MELEE_ATTACK2",
            "COND_GIVE_WAY",
            "COND_HEAR_COMBAT",
            "COND_HEAR_DANGER",
            "COND_HEAR_PLAYER",
            "COND_NEW_ENEMY",
            "COND_SEE_ENEMY",
            "COND_SEE_FEAR",
            "COND_LIGHT_DAMAGE",
            "COND_HEAVY_DAMAGE",
            "COND_SMELL",
            "COND_PROVOKED",
        ],
    ),
    (
        "SCHED_COMBAT_PATROL",
        &[
            ("TASK_SET_ROUTE_SEARCH_TIME", "5"),
            ("TASK_GET_PATH_TO_RANDOM_NODE", "200"),
            ("TASK_WALK_PATH", "0"),
            ("TASK_WAIT_FOR_MOVEMENT", "0"),
        ],
        &[
            "COND_CAN_RANGE_ATTACK1",
            "COND_CAN_RANGE_ATTACK2",
            "COND_CAN_MELEE_ATTACK1",
            "COND_CAN_MELEE_ATTACK2",
            "COND_GIVE_WAY",
            "COND_HEAR_DANGER",
            "COND_NEW_ENEMY",
        ],
    ),
    (
        "SCHED_RUN_RANDOM",
        &[
            ("TASK_SET_ROUTE_SEARCH_TIME", "1"),
            ("TASK_GET_PATH_TO_RANDOM_NODE", "500"),
            ("TASK_RUN_PATH", "0"),
            ("TASK_WAIT_FOR_MOVEMENT", "0"),
        ],
        &[],
    ),
    ("SCHED_FALL_TO_GROUND", &[("TASK_FALL_TO_GROUND", "0")], &[]),
    (
        "SCHED_DROPSHIP_DUSTOFF",
        &[
            ("TASK_WALK_PATH", "0"),
            ("TASK_WAIT_FOR_MOVEMENT", "0"),
            ("TASK_WAIT_PVS", "0"),
        ],
        &[],
    ),
    (
        "SCHED_FLINCH_PHYSICS",
        &[
            ("TASK_STOP_MOVING", "0"),
            ("TASK_PLAY_SEQUENCE", "ACTIVITY:ACT_FLINCH_PHYSICS"),
        ],
        &[],
    ),
    (
        "SCHED_MOVE_AWAY_FROM_ENEMY",
        &[
            ("TASK_SET_FAIL_SCHEDULE", "SCHEDULE:SCHED_MOVE_AWAY_FAIL"),
            ("TASK_FACE_ENEMY", "0"),
            ("TASK_MOVE_AWAY_PATH", "120"),
            ("TASK_RUN_PATH", "0"),
            ("TASK_WAIT_FOR_MOVEMENT", "0"),
            ("TASK_SET_SCHEDULE", "SCHEDULE:SCHED_MOVE_AWAY_END"),
        ],
        &[
            "COND_NEW_ENEMY",
            "COND_CAN_RANGE_ATTACK1",
            "COND_CAN_RANGE_ATTACK2",
            "COND_CAN_MELEE_ATTACK1",
            "COND_CAN_MELEE_ATTACK2",
        ],
    ),
    (
        "SCHED_MOVE_AWAY",
        &[
            ("TASK_SET_FAIL_SCHEDULE", "SCHEDULE:SCHED_MOVE_AWAY_FAIL"),
            ("TASK_MOVE_AWAY_PATH", "120"),
            ("TASK_RUN_PATH", "0"),
            ("TASK_WAIT_FOR_MOVEMENT", "0"),
            ("TASK_SET_SCHEDULE", "SCHEDULE:SCHED_MOVE_AWAY_END"),
        ],
        &[],
    ),
    ("SCHED_MOVE_AWAY_FAIL", &[("TASK_STOP_MOVING", "0")], &[]),
    (
        "SCHED_MOVE_AWAY_END",
        &[("TASK_STOP_MOVING", "0"), ("TASK_FACE_REASONABLE", "0")],
        &[
            "COND_NEW_ENEMY",
            "COND_SEE_ENEMY",
            "COND_SEE_FEAR",
            "COND_LIGHT_DAMAGE",
            "COND_HEAVY_DAMAGE",
            "COND_PROVOKED",
            "COND_SMELL",
            "COND_HEAR_COMBAT",
            "COND_HEAR_WORLD",
            "COND_HEAR_PLAYER",
            "COND_HEAR_DANGER",
            "COND_HEAR_BULLET_IMPACT",
            "COND_IDLE_INTERRUPT",
        ],
    ),
    (
        "SCHED_WAIT_FOR_SPEAK_FINISH",
        &[("TASK_WAIT_FOR_SPEAK_FINISH", "0")],
        &[
            "COND_NEW_ENEMY",
            "COND_SEE_FEAR",
            "COND_LIGHT_DAMAGE",
            "COND_HEAVY_DAMAGE",
            "COND_SMELL",
            "COND_PROVOKED",
            "COND_GIVE_WAY",
            "COND_HEAR_DANGER",
            "COND_HEAR_COMBAT",
            "COND_HEAR_BULLET_IMPACT",
        ],
    ),
    (
        "SCHED_DUCK_DODGE",
        &[
            ("TASK_STOP_MOVING", "0"),
            ("TASK_PLAY_SEQUENCE", "ACTIVITY:ACT_DUCK_DODGE"),
            ("TASK_DEFER_DODGE", "30"),
        ],
        &[],
    ),
    (
        "SCHED_INTERACTION_MOVE_TO_PARTNER",
        &[
            ("TASK_GET_PATH_TO_INTERACTION_PARTNER", "0"),
            ("TASK_FACE_TARGET", "0"),
            ("TASK_WAIT", "1"),
        ],
        &["COND_NO_CUSTOM_INTERRUPTS"],
    ),
    (
        "SCHED_INTERACTION_WAIT_FOR_PARTNER",
        &[("TASK_FACE_TARGET", "0"), ("TASK_WAIT", "1")],
        &["COND_NO_CUSTOM_INTERRUPTS"],
    ),
    (
        "SCHED_SLEEP",
        &[("TASK_STOP_MOVING", "0"), ("TASK_WAIT", "0.2")],
        &[],
    ),
];
