//! Class_T (baseentity.h, HL2_DLL) and CHalfLife2::InitDefaultAIRelationships
//! (hl2_gamerules.cpp): every pair starts D_NU 0, then the SDK table is applied in order.
//! The table rows are data taken from the SDK; per-entity overrides (ai_relationship,
//! AddEntityRelationship) are separate.
use serde::Serialize;

#[derive(Clone, Copy, Debug, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize)]
pub enum Class {
    None,
    Player,
    PlayerAlly,
    PlayerAllyVital,
    Antlion,
    Barnacle,
    Bullseye,
    CitizenPassive,
    CitizenRebel,
    Combine,
    CombineGunship,
    Conscript,
    Headcrab,
    Manhack,
    Metropolice,
    Military,
    Scanner,
    Stalker,
    Vortigaunt,
    Zombie,
    Protosniper,
    Missile,
    Flare,
    EarthFauna,
    HackedRollermine,
    CombineHunter,
}
pub const NUM_AI_CLASSES: usize = 26;

/// Disposition_t: D_ER error, D_HT hate, D_FR fear, D_LI like, D_NU neutral.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize)]
pub enum Disposition {
    ER,
    HT,
    FR,
    LI,
    NU,
}
use Class::*;
use Disposition::*;

const TABLE: &[(Class, Class, Disposition, i32)] = &[
    (Antlion, None, NU, 0),
    (Antlion, Player, HT, 0),
    (Antlion, Barnacle, NU, 0),
    (Antlion, Bullseye, NU, 0),
    (Antlion, CitizenPassive, HT, 0),
    (Antlion, CitizenRebel, HT, 0),
    (Antlion, Combine, HT, 0),
    (Antlion, CombineGunship, NU, 0),
    (Antlion, CombineHunter, HT, 0),
    (Antlion, Conscript, HT, 0),
    (Antlion, Flare, NU, 0),
    (Antlion, Headcrab, HT, 0),
    (Antlion, Manhack, HT, 0),
    (Antlion, Metropolice, HT, 0),
    (Antlion, Military, HT, 0),
    (Antlion, Missile, NU, 0),
    (Antlion, Scanner, HT, 0),
    (Antlion, Stalker, HT, 0),
    (Antlion, Vortigaunt, HT, 0),
    (Antlion, Zombie, HT, 0),
    (Antlion, Protosniper, HT, 0),
    (Antlion, Antlion, LI, 0),
    (Antlion, EarthFauna, NU, 0),
    (Antlion, PlayerAlly, HT, 0),
    (Antlion, PlayerAllyVital, HT, 0),
    (Antlion, HackedRollermine, HT, 0),
    (Barnacle, None, NU, 0),
    (Barnacle, Player, HT, 0),
    (Barnacle, Antlion, HT, 0),
    (Barnacle, Barnacle, LI, 0),
    (Barnacle, Bullseye, NU, 0),
    (Barnacle, CitizenPassive, HT, 0),
    (Barnacle, CitizenRebel, HT, 0),
    (Barnacle, Combine, HT, 0),
    (Barnacle, CombineGunship, NU, 0),
    (Barnacle, CombineHunter, NU, 0),
    (Barnacle, Conscript, HT, 0),
    (Barnacle, Flare, NU, 0),
    (Barnacle, Headcrab, HT, 0),
    (Barnacle, Manhack, FR, 0),
    (Barnacle, Metropolice, HT, 0),
    (Barnacle, Military, HT, 0),
    (Barnacle, Missile, NU, 0),
    (Barnacle, Scanner, NU, 0),
    (Barnacle, Stalker, HT, 0),
    (Barnacle, Vortigaunt, HT, 0),
    (Barnacle, Zombie, HT, 0),
    (Barnacle, Protosniper, NU, 0),
    (Barnacle, EarthFauna, HT, 0),
    (Barnacle, PlayerAlly, HT, 0),
    (Barnacle, PlayerAllyVital, HT, 0),
    (Barnacle, HackedRollermine, HT, 0),
    (Bullseye, None, NU, 0),
    (Bullseye, Player, NU, 0),
    (Bullseye, Antlion, NU, 0),
    (Bullseye, Barnacle, NU, 0),
    (Bullseye, Bullseye, NU, 0),
    (Bullseye, CitizenPassive, NU, 0),
    (Bullseye, CitizenRebel, NU, 0),
    (Bullseye, Combine, NU, 0),
    (Bullseye, CombineGunship, NU, 0),
    (Bullseye, CombineHunter, NU, 0),
    (Bullseye, Conscript, NU, 0),
    (Bullseye, Flare, NU, 0),
    (Bullseye, Headcrab, NU, 0),
    (Bullseye, Manhack, NU, 0),
    (Bullseye, Metropolice, NU, 0),
    (Bullseye, Military, NU, 0),
    (Bullseye, Missile, NU, 0),
    (Bullseye, Scanner, NU, 0),
    (Bullseye, Stalker, NU, 0),
    (Bullseye, Vortigaunt, NU, 0),
    (Bullseye, Zombie, NU, 0),
    (Bullseye, Protosniper, NU, 0),
    (Bullseye, EarthFauna, NU, 0),
    (Bullseye, PlayerAlly, NU, 0),
    (Bullseye, PlayerAllyVital, NU, 0),
    (Bullseye, HackedRollermine, NU, 0),
    (CitizenPassive, None, NU, 0),
    (CitizenPassive, Player, NU, 0),
    (CitizenPassive, Antlion, HT, 0),
    (CitizenPassive, Barnacle, FR, 0),
    (CitizenPassive, Bullseye, NU, 0),
    (CitizenPassive, CitizenPassive, NU, 0),
    (CitizenPassive, CitizenRebel, NU, 0),
    (CitizenPassive, Combine, NU, 0),
    (CitizenPassive, CombineGunship, NU, 0),
    (CitizenPassive, CombineHunter, FR, 0),
    (CitizenPassive, Conscript, NU, 0),
    (CitizenPassive, Flare, NU, 0),
    (CitizenPassive, Headcrab, FR, 0),
    (CitizenPassive, Manhack, FR, 0),
    (CitizenPassive, Metropolice, NU, 0),
    (CitizenPassive, Military, NU, 0),
    (CitizenPassive, Missile, FR, 0),
    (CitizenPassive, Scanner, NU, 0),
    (CitizenPassive, Stalker, NU, 0),
    (CitizenPassive, Vortigaunt, LI, 0),
    (CitizenPassive, Zombie, FR, 0),
    (CitizenPassive, Protosniper, NU, 0),
    (CitizenPassive, EarthFauna, NU, 0),
    (CitizenPassive, PlayerAlly, NU, 0),
    (CitizenPassive, PlayerAllyVital, NU, 0),
    (CitizenPassive, HackedRollermine, NU, 0),
    (CitizenRebel, None, NU, 0),
    (CitizenRebel, Player, NU, 0),
    (CitizenRebel, Antlion, HT, 0),
    (CitizenRebel, Barnacle, FR, 0),
    (CitizenRebel, Bullseye, NU, 0),
    (CitizenRebel, CitizenPassive, NU, 0),
    (CitizenRebel, CitizenRebel, NU, 0),
    (CitizenRebel, Combine, HT, 0),
    (CitizenRebel, CombineGunship, NU, 0),
    (CitizenRebel, CombineHunter, HT, 0),
    (CitizenRebel, Conscript, NU, 0),
    (CitizenRebel, Flare, NU, 0),
    (CitizenRebel, Headcrab, HT, 0),
    (CitizenRebel, Manhack, HT, 0),
    (CitizenRebel, Metropolice, HT, 0),
    (CitizenRebel, Military, HT, 0),
    (CitizenRebel, Missile, FR, 0),
    (CitizenRebel, Scanner, HT, 0),
    (CitizenRebel, Stalker, HT, 0),
    (CitizenRebel, Vortigaunt, LI, 0),
    (CitizenRebel, Zombie, HT, 0),
    (CitizenRebel, Protosniper, NU, 0),
    (CitizenRebel, EarthFauna, NU, 0),
    (CitizenRebel, PlayerAlly, NU, 0),
    (CitizenRebel, PlayerAllyVital, NU, 0),
    (CitizenRebel, HackedRollermine, NU, 0),
    (Combine, None, NU, 0),
    (Combine, Player, HT, 0),
    (Combine, Antlion, HT, 0),
    (Combine, Barnacle, FR, 0),
    (Combine, Bullseye, NU, 0),
    (Combine, CitizenPassive, NU, 0),
    (Combine, CitizenRebel, HT, 0),
    (Combine, Combine, LI, 0),
    (Combine, CombineGunship, LI, 0),
    (Combine, CombineHunter, LI, 0),
    (Combine, Conscript, HT, 0),
    (Combine, Flare, NU, 0),
    (Combine, Headcrab, HT, 0),
    (Combine, Manhack, NU, 0),
    (Combine, Metropolice, NU, 0),
    (Combine, Military, NU, 0),
    (Combine, Missile, NU, 0),
    (Combine, Scanner, NU, 0),
    (Combine, Stalker, NU, 0),
    (Combine, Vortigaunt, HT, 0),
    (Combine, Zombie, HT, 0),
    (Combine, Protosniper, NU, 0),
    (Combine, EarthFauna, NU, 0),
    (Combine, PlayerAlly, HT, 0),
    (Combine, PlayerAllyVital, HT, 0),
    (Combine, HackedRollermine, HT, 0),
    (CombineGunship, None, NU, 0),
    (CombineGunship, Player, HT, 0),
    (CombineGunship, Antlion, HT, 0),
    (CombineGunship, Barnacle, NU, 0),
    (CombineGunship, Bullseye, NU, 0),
    (CombineGunship, CitizenPassive, NU, 0),
    (CombineGunship, CitizenRebel, HT, 0),
    (CombineGunship, Combine, LI, 0),
    (CombineGunship, CombineGunship, LI, 0),
    (CombineGunship, CombineHunter, LI, 0),
    (CombineGunship, Conscript, HT, 0),
    (CombineGunship, Flare, NU, 0),
    (CombineGunship, Headcrab, NU, 0),
    (CombineGunship, Manhack, NU, 0),
    (CombineGunship, Metropolice, NU, 0),
    (CombineGunship, Military, NU, 0),
    (CombineGunship, Missile, FR, 0),
    (CombineGunship, Scanner, NU, 0),
    (CombineGunship, Stalker, NU, 0),
    (CombineGunship, Vortigaunt, HT, 0),
    (CombineGunship, Zombie, HT, 0),
    (CombineGunship, Protosniper, NU, 0),
    (CombineGunship, EarthFauna, NU, 0),
    (CombineGunship, PlayerAlly, HT, 0),
    (CombineGunship, PlayerAllyVital, HT, 0),
    (CombineGunship, HackedRollermine, HT, 0),
    (CombineHunter, None, NU, 0),
    (CombineHunter, Player, HT, 0),
    (CombineHunter, Antlion, HT, 0),
    (CombineHunter, Barnacle, NU, 0),
    (CombineHunter, Bullseye, NU, 0),
    (CombineHunter, CitizenPassive, HT, 0),
    (CombineHunter, CitizenRebel, HT, 0),
    (CombineHunter, Combine, LI, 0),
    (CombineHunter, CombineGunship, LI, 0),
    (CombineHunter, CombineHunter, LI, 0),
    (CombineHunter, Conscript, HT, 0),
    (CombineHunter, Flare, NU, 0),
    (CombineHunter, Headcrab, HT, 0),
    (CombineHunter, Manhack, NU, 0),
    (CombineHunter, Metropolice, NU, 0),
    (CombineHunter, Military, NU, 0),
    (CombineHunter, Missile, NU, 0),
    (CombineHunter, Scanner, NU, 0),
    (CombineHunter, Stalker, NU, 0),
    (CombineHunter, Vortigaunt, HT, 0),
    (CombineHunter, Zombie, HT, 0),
    (CombineHunter, Protosniper, NU, 0),
    (CombineHunter, EarthFauna, NU, 0),
    (CombineHunter, PlayerAlly, HT, 0),
    (CombineHunter, PlayerAllyVital, HT, 0),
    (CombineHunter, HackedRollermine, HT, 0),
    (Conscript, None, NU, 0),
    (Conscript, Player, NU, 0),
    (Conscript, Antlion, HT, 0),
    (Conscript, Barnacle, FR, 0),
    (Conscript, Bullseye, NU, 0),
    (Conscript, CitizenPassive, NU, 0),
    (Conscript, CitizenRebel, NU, 0),
    (Conscript, Combine, HT, 0),
    (Conscript, CombineGunship, NU, 0),
    (Conscript, CombineHunter, HT, 0),
    (Conscript, Conscript, NU, 0),
    (Conscript, Flare, NU, 0),
    (Conscript, Headcrab, HT, 0),
    (Conscript, Manhack, HT, 0),
    (Conscript, Metropolice, HT, 0),
    (Conscript, Military, HT, 0),
    (Conscript, Missile, NU, 0),
    (Conscript, Scanner, HT, 0),
    (Conscript, Stalker, HT, 0),
    (Conscript, Vortigaunt, NU, 0),
    (Conscript, Zombie, HT, 0),
    (Conscript, Protosniper, NU, 0),
    (Conscript, EarthFauna, NU, 0),
    (Conscript, PlayerAlly, NU, 0),
    (Conscript, PlayerAllyVital, NU, 0),
    (Conscript, HackedRollermine, NU, 0),
    (Flare, None, NU, 0),
    (Flare, Player, NU, 0),
    (Flare, Antlion, NU, 0),
    (Flare, Barnacle, NU, 0),
    (Flare, Bullseye, NU, 0),
    (Flare, CitizenPassive, NU, 0),
    (Flare, CitizenRebel, NU, 0),
    (Flare, Combine, NU, 0),
    (Flare, CombineGunship, NU, 0),
    (Flare, CombineHunter, NU, 0),
    (Flare, Conscript, NU, 0),
    (Flare, Flare, NU, 0),
    (Flare, Headcrab, NU, 0),
    (Flare, Manhack, NU, 0),
    (Flare, Metropolice, NU, 0),
    (Flare, Military, NU, 0),
    (Flare, Missile, NU, 0),
    (Flare, Flare, NU, 0),
    (Flare, Scanner, NU, 0),
    (Flare, Stalker, NU, 0),
    (Flare, Vortigaunt, NU, 0),
    (Flare, Zombie, NU, 0),
    (Flare, Protosniper, NU, 0),
    (Flare, EarthFauna, NU, 0),
    (Flare, PlayerAlly, NU, 0),
    (Flare, PlayerAllyVital, NU, 0),
    (Flare, HackedRollermine, NU, 0),
    (Headcrab, None, NU, 0),
    (Headcrab, Player, HT, 0),
    (Headcrab, Antlion, HT, 0),
    (Headcrab, Barnacle, NU, 0),
    (Headcrab, Bullseye, NU, 0),
    (Headcrab, CitizenPassive, HT, 0),
    (Headcrab, CitizenRebel, HT, 0),
    (Headcrab, Combine, HT, 0),
    (Headcrab, CombineGunship, NU, 0),
    (Headcrab, CombineHunter, NU, 0),
    (Headcrab, Conscript, HT, 0),
    (Headcrab, Flare, NU, 0),
    (Headcrab, Headcrab, NU, 0),
    (Headcrab, Manhack, NU, 0),
    (Headcrab, Metropolice, HT, 0),
    (Headcrab, Military, NU, 0),
    (Headcrab, Missile, NU, 0),
    (Headcrab, Scanner, NU, 0),
    (Headcrab, Stalker, NU, 0),
    (Headcrab, Vortigaunt, HT, 0),
    (Headcrab, Zombie, NU, 0),
    (Headcrab, Protosniper, NU, 0),
    (Headcrab, EarthFauna, NU, 0),
    (Headcrab, PlayerAlly, HT, 0),
    (Headcrab, PlayerAllyVital, HT, 0),
    (Headcrab, HackedRollermine, FR, 0),
    (Manhack, None, NU, 0),
    (Manhack, Player, HT, 0),
    (Manhack, Antlion, HT, 0),
    (Manhack, Barnacle, NU, 0),
    (Manhack, Bullseye, NU, 0),
    (Manhack, CitizenPassive, HT, 0),
    (Manhack, CitizenRebel, HT, 0),
    (Manhack, Combine, NU, 0),
    (Manhack, CombineGunship, NU, 0),
    (Manhack, CombineHunter, NU, 0),
    (Manhack, Conscript, HT, 0),
    (Manhack, Flare, NU, 0),
    (Manhack, Headcrab, HT, -1),
    (Manhack, Manhack, NU, 0),
    (Manhack, Metropolice, NU, 0),
    (Manhack, Military, NU, 0),
    (Manhack, Missile, NU, 0),
    (Manhack, Scanner, NU, 0),
    (Manhack, Stalker, NU, 0),
    (Manhack, Vortigaunt, HT, 0),
    (Manhack, Zombie, HT, 0),
    (Manhack, Protosniper, NU, 0),
    (Manhack, EarthFauna, NU, 0),
    (Manhack, PlayerAlly, HT, 0),
    (Manhack, PlayerAllyVital, HT, 0),
    (Manhack, HackedRollermine, HT, 0),
    (Metropolice, None, NU, 0),
    (Metropolice, Player, HT, 0),
    (Metropolice, Antlion, HT, 0),
    (Metropolice, Barnacle, NU, 0),
    (Metropolice, Bullseye, NU, 0),
    (Metropolice, CitizenPassive, NU, 0),
    (Metropolice, CitizenRebel, HT, 0),
    (Metropolice, Combine, NU, 0),
    (Metropolice, CombineGunship, NU, 0),
    (Metropolice, CombineHunter, NU, 0),
    (Metropolice, Conscript, HT, 0),
    (Metropolice, Flare, NU, 0),
    (Metropolice, Headcrab, HT, 0),
    (Metropolice, Manhack, NU, 0),
    (Metropolice, Metropolice, NU, 0),
    (Metropolice, Military, NU, 0),
    (Metropolice, Missile, NU, 0),
    (Metropolice, Scanner, NU, 0),
    (Metropolice, Stalker, NU, 0),
    (Metropolice, Vortigaunt, HT, 0),
    (Metropolice, Zombie, HT, 0),
    (Metropolice, Protosniper, NU, 0),
    (Metropolice, EarthFauna, NU, 0),
    (Metropolice, PlayerAlly, HT, 0),
    (Metropolice, PlayerAllyVital, HT, 0),
    (Metropolice, HackedRollermine, HT, 0),
    (Military, None, NU, 0),
    (Military, Player, HT, 0),
    (Military, Antlion, HT, 0),
    (Military, Barnacle, NU, 0),
    (Military, Bullseye, NU, 0),
    (Military, CitizenPassive, NU, 0),
    (Military, CitizenRebel, HT, 0),
    (Military, Combine, NU, 0),
    (Military, CombineGunship, NU, 0),
    (Military, CombineHunter, NU, 0),
    (Military, Conscript, HT, 0),
    (Military, Flare, NU, 0),
    (Military, Headcrab, HT, 0),
    (Military, Manhack, NU, 0),
    (Military, Metropolice, NU, 0),
    (Military, Military, NU, 0),
    (Military, Missile, NU, 0),
    (Military, Scanner, NU, 0),
    (Military, Stalker, NU, 0),
    (Military, Vortigaunt, HT, 0),
    (Military, Zombie, HT, 0),
    (Military, Protosniper, NU, 0),
    (Military, EarthFauna, NU, 0),
    (Military, PlayerAlly, HT, 0),
    (Military, PlayerAllyVital, HT, 0),
    (Military, HackedRollermine, HT, 0),
    (Missile, None, NU, 0),
    (Missile, Player, HT, 0),
    (Missile, Antlion, HT, 0),
    (Missile, Barnacle, NU, 0),
    (Missile, Bullseye, NU, 0),
    (Missile, CitizenPassive, NU, 0),
    (Missile, CitizenRebel, HT, 0),
    (Missile, Combine, NU, 0),
    (Missile, CombineGunship, NU, 0),
    (Missile, CombineHunter, NU, 0),
    (Missile, Conscript, HT, 0),
    (Missile, Flare, NU, 0),
    (Missile, Headcrab, HT, 0),
    (Missile, Manhack, NU, 0),
    (Missile, Metropolice, NU, 0),
    (Missile, Military, NU, 0),
    (Missile, Missile, NU, 0),
    (Missile, Scanner, NU, 0),
    (Missile, Stalker, NU, 0),
    (Missile, Vortigaunt, HT, 0),
    (Missile, Zombie, HT, 0),
    (Missile, Protosniper, NU, 0),
    (Missile, EarthFauna, NU, 0),
    (Missile, PlayerAlly, HT, 0),
    (Missile, PlayerAllyVital, HT, 0),
    (Missile, HackedRollermine, HT, 0),
    (None, None, NU, 0),
    (None, Player, NU, 0),
    (None, Antlion, NU, 0),
    (None, Barnacle, NU, 0),
    (None, Bullseye, NU, 0),
    (None, CitizenPassive, NU, 0),
    (None, CitizenRebel, NU, 0),
    (None, Combine, NU, 0),
    (None, CombineGunship, NU, 0),
    (None, CombineHunter, NU, 0),
    (None, Conscript, NU, 0),
    (None, Flare, NU, 0),
    (None, Headcrab, NU, 0),
    (None, Manhack, NU, 0),
    (None, Metropolice, NU, 0),
    (None, Military, NU, 0),
    (None, Scanner, NU, 0),
    (None, Stalker, NU, 0),
    (None, Vortigaunt, NU, 0),
    (None, Zombie, NU, 0),
    (None, Protosniper, NU, 0),
    (None, EarthFauna, NU, 0),
    (None, PlayerAlly, NU, 0),
    (None, PlayerAllyVital, NU, 0),
    (None, HackedRollermine, NU, 0),
    (Player, None, NU, 0),
    (Player, Player, NU, 0),
    (Player, Antlion, HT, 0),
    (Player, Barnacle, HT, 0),
    (Player, Bullseye, HT, 0),
    (Player, CitizenPassive, LI, 0),
    (Player, CitizenRebel, LI, 0),
    (Player, Combine, HT, 0),
    (Player, CombineGunship, HT, 0),
    (Player, CombineHunter, HT, 0),
    (Player, Conscript, NU, 0),
    (Player, Flare, NU, 0),
    (Player, Headcrab, HT, 0),
    (Player, Manhack, HT, 0),
    (Player, Metropolice, HT, 0),
    (Player, Military, HT, 0),
    (Player, Missile, NU, 0),
    (Player, Scanner, HT, 0),
    (Player, Stalker, HT, 0),
    (Player, Vortigaunt, LI, 0),
    (Player, Zombie, HT, 0),
    (Player, Protosniper, HT, 0),
    (Player, EarthFauna, NU, 0),
    (Player, PlayerAlly, LI, 0),
    (Player, PlayerAllyVital, LI, 0),
    (Player, HackedRollermine, LI, 0),
    (PlayerAlly, None, NU, 0),
    (PlayerAlly, Player, LI, 0),
    (PlayerAlly, Antlion, HT, 0),
    (PlayerAlly, Barnacle, HT, 0),
    (PlayerAlly, Bullseye, NU, 0),
    (PlayerAlly, CitizenPassive, NU, 0),
    (PlayerAlly, CitizenRebel, NU, 0),
    (PlayerAlly, Combine, HT, 0),
    (PlayerAlly, CombineGunship, NU, 0),
    (PlayerAlly, CombineHunter, HT, 0),
    (PlayerAlly, Conscript, NU, 0),
    (PlayerAlly, Flare, NU, 0),
    (PlayerAlly, Headcrab, FR, 0),
    (PlayerAlly, Manhack, HT, 0),
    (PlayerAlly, Metropolice, HT, 0),
    (PlayerAlly, Military, HT, 0),
    (PlayerAlly, Missile, NU, 0),
    (PlayerAlly, Scanner, HT, 0),
    (PlayerAlly, Stalker, HT, 0),
    (PlayerAlly, Vortigaunt, LI, 0),
    (PlayerAlly, Zombie, FR, 1),
    (PlayerAlly, Protosniper, FR, 0),
    (PlayerAlly, EarthFauna, NU, 0),
    (PlayerAlly, PlayerAlly, LI, 0),
    (PlayerAlly, PlayerAllyVital, LI, 0),
    (PlayerAlly, HackedRollermine, LI, 0),
    (PlayerAllyVital, None, NU, 0),
    (PlayerAllyVital, Player, LI, 0),
    (PlayerAllyVital, Antlion, HT, 0),
    (PlayerAllyVital, Barnacle, HT, 0),
    (PlayerAllyVital, Bullseye, NU, 0),
    (PlayerAllyVital, CitizenPassive, NU, 0),
    (PlayerAllyVital, CitizenRebel, NU, 0),
    (PlayerAllyVital, Combine, HT, 0),
    (PlayerAllyVital, CombineGunship, NU, 0),
    (PlayerAllyVital, CombineHunter, FR, 0),
    (PlayerAllyVital, Conscript, NU, 0),
    (PlayerAllyVital, Flare, NU, 0),
    (PlayerAllyVital, Headcrab, HT, 0),
    (PlayerAllyVital, Manhack, HT, 0),
    (PlayerAllyVital, Metropolice, HT, 0),
    (PlayerAllyVital, Military, HT, 0),
    (PlayerAllyVital, Missile, NU, 0),
    (PlayerAllyVital, Scanner, HT, 0),
    (PlayerAllyVital, Stalker, HT, 0),
    (PlayerAllyVital, Vortigaunt, LI, 0),
    (PlayerAllyVital, Zombie, HT, 0),
    (PlayerAllyVital, Protosniper, FR, 0),
    (PlayerAllyVital, EarthFauna, NU, 0),
    (PlayerAllyVital, PlayerAlly, LI, 0),
    (PlayerAllyVital, PlayerAllyVital, LI, 0),
    (PlayerAllyVital, HackedRollermine, LI, 0),
    (Scanner, None, NU, 0),
    (Scanner, Player, HT, 0),
    (Scanner, Antlion, HT, 0),
    (Scanner, Barnacle, NU, 0),
    (Scanner, Bullseye, NU, 0),
    (Scanner, CitizenPassive, NU, 0),
    (Scanner, CitizenRebel, HT, 0),
    (Scanner, Combine, LI, 0),
    (Scanner, CombineGunship, LI, 0),
    (Scanner, CombineHunter, LI, 0),
    (Scanner, Conscript, HT, 0),
    (Scanner, Flare, NU, 0),
    (Scanner, Headcrab, NU, 0),
    (Scanner, Manhack, LI, 0),
    (Scanner, Metropolice, LI, 0),
    (Scanner, Military, LI, 0),
    (Scanner, Missile, NU, 0),
    (Scanner, Scanner, LI, 0),
    (Scanner, Stalker, LI, 0),
    (Scanner, Vortigaunt, HT, 0),
    (Scanner, Zombie, NU, 0),
    (Scanner, Protosniper, LI, 0),
    (Scanner, EarthFauna, NU, 0),
    (Scanner, PlayerAlly, HT, 0),
    (Scanner, PlayerAllyVital, HT, 0),
    (Scanner, HackedRollermine, HT, 0),
    (Stalker, None, NU, 0),
    (Stalker, Player, HT, 0),
    (Stalker, Antlion, HT, 0),
    (Stalker, Barnacle, NU, 0),
    (Stalker, Bullseye, NU, 0),
    (Stalker, CitizenPassive, NU, 0),
    (Stalker, CitizenRebel, HT, 0),
    (Stalker, Combine, NU, 0),
    (Stalker, CombineGunship, NU, 0),
    (Stalker, CombineHunter, NU, 0),
    (Stalker, Conscript, HT, 0),
    (Stalker, Flare, NU, 0),
    (Stalker, Headcrab, NU, 0),
    (Stalker, Manhack, NU, 0),
    (Stalker, Metropolice, NU, 0),
    (Stalker, Military, NU, 0),
    (Stalker, Missile, NU, 0),
    (Stalker, Scanner, NU, 0),
    (Stalker, Stalker, NU, 0),
    (Stalker, Vortigaunt, HT, 0),
    (Stalker, Zombie, NU, 0),
    (Stalker, Protosniper, NU, 0),
    (Stalker, EarthFauna, NU, 0),
    (Stalker, PlayerAlly, HT, 0),
    (Stalker, PlayerAllyVital, HT, 0),
    (Stalker, HackedRollermine, HT, 0),
    (Vortigaunt, None, NU, 0),
    (Vortigaunt, Player, LI, 0),
    (Vortigaunt, Antlion, HT, 0),
    (Vortigaunt, Barnacle, FR, 0),
    (Vortigaunt, Bullseye, NU, 0),
    (Vortigaunt, CitizenPassive, LI, 0),
    (Vortigaunt, CitizenRebel, LI, 0),
    (Vortigaunt, Combine, HT, 0),
    (Vortigaunt, CombineGunship, NU, 0),
    (Vortigaunt, CombineHunter, HT, 0),
    (Vortigaunt, Conscript, NU, 0),
    (Vortigaunt, Flare, NU, 0),
    (Vortigaunt, Headcrab, HT, 0),
    (Vortigaunt, Manhack, HT, 0),
    (Vortigaunt, Metropolice, HT, 0),
    (Vortigaunt, Military, HT, 0),
    (Vortigaunt, Missile, NU, 0),
    (Vortigaunt, Scanner, HT, 0),
    (Vortigaunt, Stalker, HT, 0),
    (Vortigaunt, Vortigaunt, NU, 0),
    (Vortigaunt, Zombie, HT, 0),
    (Vortigaunt, Protosniper, NU, 0),
    (Vortigaunt, EarthFauna, NU, 0),
    (Vortigaunt, PlayerAlly, LI, 0),
    (Vortigaunt, PlayerAllyVital, LI, 0),
    (Vortigaunt, HackedRollermine, LI, 0),
    (Zombie, None, NU, 0),
    (Zombie, Player, HT, 0),
    (Zombie, Antlion, HT, 0),
    (Zombie, Barnacle, NU, 0),
    (Zombie, Bullseye, NU, 0),
    (Zombie, CitizenPassive, HT, 0),
    (Zombie, CitizenRebel, HT, 0),
    (Zombie, Combine, HT, 0),
    (Zombie, CombineGunship, NU, 0),
    (Zombie, CombineHunter, HT, 0),
    (Zombie, Conscript, HT, 0),
    (Zombie, Flare, NU, 0),
    (Zombie, Headcrab, NU, 0),
    (Zombie, Manhack, FR, 0),
    (Zombie, Metropolice, HT, 0),
    (Zombie, Military, FR, 0),
    (Zombie, Missile, NU, 0),
    (Zombie, Scanner, NU, 0),
    (Zombie, Stalker, NU, 0),
    (Zombie, Vortigaunt, HT, 0),
    (Zombie, Zombie, NU, 0),
    (Zombie, Protosniper, NU, 0),
    (Zombie, EarthFauna, NU, 0),
    (Zombie, PlayerAlly, HT, 0),
    (Zombie, PlayerAllyVital, HT, 0),
    (Zombie, HackedRollermine, HT, 0),
    (Protosniper, None, NU, 0),
    (Protosniper, Player, HT, 0),
    (Protosniper, Antlion, HT, 0),
    (Protosniper, Barnacle, NU, 0),
    (Protosniper, Bullseye, NU, 0),
    (Protosniper, CitizenPassive, HT, 0),
    (Protosniper, CitizenRebel, HT, 0),
    (Protosniper, Combine, NU, 0),
    (Protosniper, CombineGunship, NU, 0),
    (Protosniper, CombineHunter, NU, 0),
    (Protosniper, Conscript, HT, 0),
    (Protosniper, Flare, NU, 0),
    (Protosniper, Headcrab, HT, 0),
    (Protosniper, Manhack, NU, 0),
    (Protosniper, Metropolice, NU, 0),
    (Protosniper, Military, NU, 0),
    (Protosniper, Missile, NU, 5),
    (Protosniper, Scanner, NU, 0),
    (Protosniper, Stalker, NU, 0),
    (Protosniper, Vortigaunt, HT, 0),
    (Protosniper, Zombie, HT, 0),
    (Protosniper, Protosniper, NU, 0),
    (Protosniper, EarthFauna, NU, 0),
    (Protosniper, PlayerAlly, HT, 0),
    (Protosniper, PlayerAllyVital, HT, 0),
    (Protosniper, HackedRollermine, HT, 0),
    (EarthFauna, None, HT, 0),
    (EarthFauna, Player, HT, 0),
    (EarthFauna, Antlion, HT, 0),
    (EarthFauna, Barnacle, NU, 0),
    (EarthFauna, Bullseye, NU, 0),
    (EarthFauna, CitizenPassive, HT, 0),
    (EarthFauna, CitizenRebel, HT, 0),
    (EarthFauna, Combine, HT, 0),
    (EarthFauna, CombineGunship, HT, 0),
    (EarthFauna, CombineHunter, HT, 0),
    (EarthFauna, Conscript, HT, 0),
    (EarthFauna, Flare, HT, 0),
    (EarthFauna, Headcrab, HT, 0),
    (EarthFauna, Manhack, HT, 0),
    (EarthFauna, Metropolice, HT, 0),
    (EarthFauna, Military, HT, 0),
    (EarthFauna, Missile, HT, 0),
    (EarthFauna, Scanner, HT, 0),
    (EarthFauna, Stalker, HT, 0),
    (EarthFauna, Vortigaunt, HT, 0),
    (EarthFauna, Zombie, HT, 0),
    (EarthFauna, Protosniper, HT, 0),
    (EarthFauna, EarthFauna, NU, 0),
    (EarthFauna, PlayerAlly, HT, 0),
    (EarthFauna, PlayerAllyVital, HT, 0),
    (EarthFauna, HackedRollermine, NU, 0),
    (HackedRollermine, None, NU, 0),
    (HackedRollermine, Player, LI, 0),
    (HackedRollermine, Antlion, HT, 0),
    (HackedRollermine, Barnacle, NU, 0),
    (HackedRollermine, Bullseye, NU, 0),
    (HackedRollermine, CitizenPassive, NU, 0),
    (HackedRollermine, CitizenRebel, NU, 0),
    (HackedRollermine, Combine, HT, 0),
    (HackedRollermine, CombineGunship, NU, 0),
    (HackedRollermine, CombineHunter, NU, 0),
    (HackedRollermine, Conscript, NU, 0),
    (HackedRollermine, Flare, NU, 0),
    (HackedRollermine, Headcrab, HT, 0),
    (HackedRollermine, Manhack, NU, 0),
    (HackedRollermine, Metropolice, HT, 0),
    (HackedRollermine, Military, HT, 0),
    (HackedRollermine, Missile, NU, 0),
    (HackedRollermine, Scanner, NU, 0),
    (HackedRollermine, Stalker, HT, 0),
    (HackedRollermine, Vortigaunt, LI, 0),
    (HackedRollermine, Zombie, HT, 1),
    (HackedRollermine, Protosniper, NU, 0),
    (HackedRollermine, EarthFauna, HT, 0),
    (HackedRollermine, PlayerAlly, LI, 0),
    (HackedRollermine, PlayerAllyVital, LI, 0),
    (HackedRollermine, HackedRollermine, LI, 0),
];

/// The default relationship table.
#[derive(Clone, Debug)]
pub struct Relationships {
    table: [[(Disposition, i32); NUM_AI_CLASSES]; NUM_AI_CLASSES],
}
impl Default for Relationships {
    fn default() -> Self {
        let mut table = [[(NU, 0); NUM_AI_CLASSES]; NUM_AI_CLASSES];
        for (subject, target, disposition, priority) in TABLE {
            table[*subject as usize][*target as usize] = (*disposition, *priority);
        }
        Self { table }
    }
}
impl Relationships {
    /// IRelationType / IRelationPriority between classes.
    pub fn get(&self, subject: Class, target: Class) -> (Disposition, i32) {
        self.table[subject as usize][target as usize]
    }
}

/// Classify() for the HL2 entity classes this project spawns. Checked against the SDK
/// for npc_metropolice, npc_combine_s and npc_citizen; the rest are unchecked defaults.
/// Citizens: CNPC_Citizen::Classify returns CLASS_CITIZEN_PASSIVE while the globals
/// "gordon_precriminal" or "citizens_passive" are on, else CLASS_PLAYER_ALLY.
pub fn classify(classname: &str, precriminal: bool) -> Class {
    match classname {
        "player" => Player,
        "npc_metropolice" => Metropolice,
        "npc_combine_s" => Combine,
        "npc_citizen" => {
            if precriminal {
                CitizenPassive
            } else {
                PlayerAlly
            }
        }
        "npc_alyx" | "npc_barney" | "npc_kleiner" | "npc_eli" | "npc_mossman" | "npc_monk"
        | "npc_dog" => PlayerAllyVital,
        "npc_vortigaunt" => Vortigaunt,
        "npc_antlion" | "npc_antlionguard" => Antlion,
        "npc_headcrab" | "npc_headcrab_fast" | "npc_headcrab_black" | "npc_headcrab_poison" => {
            Headcrab
        }
        "npc_zombie" | "npc_fastzombie" | "npc_poisonzombie" | "npc_zombine" => Zombie,
        "npc_manhack" => Manhack,
        "npc_cscanner" | "npc_clawscanner" => Scanner,
        "npc_stalker" => Stalker,
        "npc_barnacle" => Barnacle,
        "npc_bullseye" => Bullseye,
        "npc_combinegunship" | "npc_helicopter" | "npc_combinedropship" => CombineGunship,
        "npc_sniper" => Protosniper,
        "npc_crow" | "npc_pigeon" | "npc_seagull" => EarthFauna,
        "npc_strider" | "npc_turret_floor" | "npc_combine_camera" | "npc_turret_ceiling" => Combine,
        _ => None,
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    #[test]
    fn sdk_table_gives_the_trainstation_relationships() {
        let r = Relationships::default();
        assert_eq!(TABLE.len(), 676);
        assert_eq!(r.get(Metropolice, Player), (HT, 0));
        assert_eq!(r.get(Metropolice, CitizenPassive), (NU, 0));
        assert_eq!(r.get(Combine, Combine), (LI, 0));
        assert_eq!(r.get(Antlion, Player), (HT, 0));
        assert_eq!(r.get(PlayerAlly, Player), (LI, 0));
        assert_eq!(classify("npc_citizen", true), CitizenPassive);
        assert_eq!(classify("npc_citizen", false), PlayerAlly);
    }
}
